Repository lake-rs/lakers, pull requests merged in 2023-12, with the labels that each got.

#168 Improve ead encoding robustness
  consts/src/lib.rs
  lib/src/edhoc.rs
Labels: bug

#175 doc: Add README for shared, and link READMEs in the crates
  Cargo.toml
  crypto/Cargo.toml
  crypto/lakers-crypto-cc2538/Cargo.toml
  crypto/lakers-crypto-cryptocell310-sys/Cargo.toml
  crypto/lakers-crypto-hacspec/Cargo.toml
  crypto/lakers-crypto-psa/Cargo.toml
  crypto/lakers-crypto-rustcrypto/Cargo.toml
  ead/Cargo.toml
  ead/lakers-ead-none/Cargo.toml
  ead/lakers-ead-zeroconf/Cargo.toml
  lib/Cargo.toml
  shared/Cargo.toml
  shared/README.md
Labels: documentation

#170 Refactor EADs to not use global state
  Cargo.toml
  ead/lakers-ead-authz/Cargo.toml
  ead/lakers-ead-authz/src/authenticator.rs
  ead/lakers-ead-authz/src/device.rs
  ead/lakers-ead-authz/src/lib.rs
  ead/lakers-ead-authz/src/server.rs
  ead/lakers-ead-authz/src/shared.rs
  ead/lakers-ead-authz/src/test_vectors.rs
Labels: enhancement, new feature

#174 Split message processing
  .github/workflows/build-and-test.yml
  Cargo.toml
  ead/Cargo.toml
  ead/lakers-ead-authz/src/authenticator.rs
  ead/lakers-ead-authz/src/device.rs
  ead/lakers-ead-authz/src/lib.rs
  ead/src/lib.rs
  examples/coap/src/bin/coapclient.rs
  examples/coap/src/bin/coapserver-coaphandler.rs
  examples/coap/src/bin/coapserver.rs
  examples/edhoc-rs-no_std/src/main.rs
  lib/Cargo.toml
  lib/src/edhoc.rs
  lib/src/lib.rs
  shared/src/lib.rs
Labels: enhancement, new feature
