Repository lake-rs/lakers, pull requests merged in 2024-01, with the labels that each got.

#186 Set initiator identity after learning R's
  examples/coap/src/bin/coapclient.rs
  examples/edhoc-rs-no_std/src/main.rs
  lib/src/lib.rs
Labels: enhancement

#188 Explicitly set credential transfer option
  examples/coap/src/bin/coapclient.rs
  examples/coap/src/bin/coapserver-coaphandler.rs
  examples/coap/src/bin/coapserver.rs
  examples/edhoc-rs-no_std/src/main.rs
  lib/src/edhoc.rs
  lib/src/lib.rs
  shared/src/lib.rs
Labels: new feature

#189 Use owned credential type
  examples/coap/src/bin/coapclient.rs
  examples/coap/src/bin/coapserver-coaphandler.rs
  examples/coap/src/bin/coapserver.rs
  examples/edhoc-rs-no_std/src/main.rs
  lib/src/edhoc.rs
  lib/src/lib.rs
  shared/src/cred.rs
  shared/src/lib.rs
Labels: enhancement

#192 Add EAD field to MAC computation
  lib/src/edhoc.rs
  shared/src/lib.rs
Labels: bug

#198 Implement C_R included in MAC_2 computation
  lib/src/edhoc.rs
  shared/src/lib.rs
Labels: new feature
