Repository lake-rs/lakers, pull requests merged in 2024-08, with the labels that each got.

#284 Towards crypto & method agility: API updates, new buffer, new credential struct
  ead/lakers-ead-authz/src/server.rs
  examples/coap/src/bin/coapclient.rs
  examples/coap/src/bin/coapserver-coaphandler.rs
  examples/coap/src/bin/coapserver.rs
  examples/lakers-c-native/main.c
  examples/lakers-no_std/src/main.rs
  lakers-c/cbindgen.toml
  lakers-c/src/ead_authz.rs
  lakers-c/src/initiator.rs
  lakers-c/src/lib.rs
  lakers-python/src/ead_authz/server.rs
  lakers-python/src/initiator.rs
  lakers-python/src/lib.rs
  lakers-python/src/responder.rs
  lakers-python/test/test_lakers.py
  lakers-python/test_requirements.txt
  lib/src/edhoc.rs
  lib/src/lib.rs
  shared/Cargo.toml
  shared/cbindgen.toml
  shared/src/buffer.rs
  shared/src/cred.rs
  shared/src/crypto.rs
  shared/src/lib.rs
  shared/src/python_bindings.rs
Labels: new feature

#291 More Python targets: 3.13, pypy3.10
  .github/workflows/python-wheels.yml
Labels: enhancement, depends-on-third-party

#306 python: emit logs up from rust
  .gitignore
  ead/lakers-ead-authz/Cargo.toml
  ead/lakers-ead-authz/src/authenticator.rs
  ead/lakers-ead-authz/src/device.rs
  ead/lakers-ead-authz/src/server.rs
  examples/coap/Cargo.toml
  lakers-python/Cargo.toml
  lakers-python/README.md
  lakers-python/src/ead_authz/authenticator.rs
  lakers-python/src/ead_authz/device.rs
  lakers-python/src/ead_authz/server.rs
  lakers-python/src/initiator.rs
  lakers-python/src/lib.rs
  lakers-python/src/responder.rs
Labels: enhancement
