Repository lake-rs/lakers, pull requests merged in 2024-03, with the labels that each got.

#231 Add cpp_compat for C headers
  lakers-c/cbindgen.toml
  shared/cbindgen.toml
Labels: enhancement, lakers-c

#243 Fixing hkdf_expand in crypto/psa
  crypto/Cargo.toml
  crypto/lakers-crypto-psa/src/lib.rs
  crypto/src/lib.rs
Labels: bug

#240 Towards safer code in the FFI
  examples/lakers-c-native/Makefile
  examples/lakers-c-native/README.md
  examples/lakers-c-native/main.c
  lakers-c/src/initiator.rs
  lakers-c/src/lib.rs
  lib/src/edhoc.rs
Labels: lakers-c

#244 EAD Authz: improvements/refactor in C and Python
  .gitignore
  examples/lakers-c-native/main.c
  lakers-c/src/ead_authz.rs
  lakers-python/src/initiator.rs
  lakers-python/src/responder.rs
Labels: enhancement

#245 lakers-c: check/fetch credential outside parse msg 2
  examples/lakers-c-native/main.c
  lakers-c/src/initiator.rs
  lakers-c/src/lib.rs
  lib/src/lib.rs
Labels: enhancement

#247 Remove obsolete cc2538 backend and examples
  Cargo.toml
  crypto/Cargo.toml
  crypto/lakers-crypto-cc2538/.cargo/config.toml
  crypto/lakers-crypto-cc2538/Cargo.toml
  crypto/lakers-crypto-cc2538/lib.rs.old
  crypto/lakers-crypto-cc2538/memory.x
  crypto/lakers-crypto-cc2538/sections_remote.x
  crypto/lakers-crypto-cc2538/src/lib.rs
  crypto/src/lib.rs
  examples/lakers-cc2538/.cargo/config.toml
  examples/lakers-cc2538/Cargo.toml
  examples/lakers-cc2538/build.rs
  examples/lakers-cc2538/flash.sh
  examples/lakers-cc2538/gdb.sh
  examples/lakers-cc2538/gdb_commands.gdb
  examples/lakers-cc2538/jlink_commands.jlink
  examples/lakers-cc2538/jlink_server.sh
  examples/lakers-cc2538/memory.x
  examples/lakers-cc2538/rtt.sh
  examples/lakers-cc2538/rust-toolchain
  examples/lakers-cc2538/sections_remote.x
  examples/lakers-cc2538/src/main.rs
Labels: cleanup

#249 Crypto: remove hacspec backend
  Cargo.toml
  README.md
  crypto/Cargo.toml
  crypto/lakers-crypto-hacspec/Cargo.toml
  crypto/lakers-crypto-hacspec/src/lib.rs
  crypto/src/lib.rs
  examples/lakers-no_std/src/main.rs
Labels: cleanup
